<<<<<<< HEAD
title: Katie Ha
logo: ./images/logo.png
description: Passionate and motivated by data science where I can extract and deploy the meanings behind data to deliver insights that help improving business processes and business models. Aiming to merge my background in operations management, execution, leadership in the role of Data Analyst to significant enterprise growth using big data.
author: katie_ha

show_downloads: false
theme: jekyll-theme-minimal


